# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

# app/config/services.yml
services:

    app.cow_request_service:
        class: AppBundle\Services\CowRequestService

    app.calculate_cow_cost:
        class: AppBundle\Services\CalculateCowCostService